name: WyrdShout
main: com.check.me.WyrdShout
version: 0.3
author: Highace2
website: http://WyrdCraft.enjin.com
description: Shout plugin to display message to everybody on the server
database: false
depend: [PermissionsEx]

commands:
    wshout:
        description: Shout out your message to the server
        aliases: [ws, shout, wyrdshout]
    wmute:
        description: Mute a player for a certain amount of time
        aliases: [wm, wyrdmute]
    wadmin:
        description: Configurate many options ingame
        aliases: [wyrdadmin, wa]