name: WyrdShout
main: com.check.me.WyrdShout
version: 0.3
author: Highace2
website: http://WyrdCraft.enjin.com
description: Shout plugin to display message to everybody on the server
database: false
depend: [PermissionsEx]

commands:
    wshout:
        description: Shout out your message to the server
        aliases: [ws, shout, wyrdshout]
    wmute:
        description: Mute a player for a certain amount of time
        aliases: [wm, wyrdmute]
    wadmin:
        description: Configurate many options ingame
        aliases: [wyrdadmin, wa]

permissions:
    wshout.*:
        description: Enable all WyrdShout functions
        children:
            wshout.shout: true
            wshout.override: true
            wshout.admin.*: true
            wshout.admin.version: true
            wshout.admin.delay: true
            wshout.admin.shout-prefix: true
            wshout.admin.namecolor: true
            wshout.admin.textcolor: true
            wshout.admin.mute: true
        default: false
    wshout.shout:
        description: Get permission to shout
        default: false
    wshout.override:
        description: Get access to override the timer
        default: false
    wshout.admin.*:
        description: Get all admin functions
        default: false
        children:
            wshout.admin.version: true
            wshout.admin.delay: true
            wshout.admin.shout-prefix: true
            wshout.admin.namecolor: true
            wshout.admin.textcolor: true
            wshout.admin.mute: true
    wshout.admin.version:
        description: Gives access to see version number
        default: false
    wshout.admin.delay:
        description: Gives access to set delay between shouts
        default: false
    wshout.admin.shout-prefix:
        description: Set shout prefix ingame
        default: false
    wshout.admin.namecolor:
        description: Set color of names ingame
        default: false
    wshout.admin.textcolor:
        description: Set color of text ingame
        default: false
    wshout.admin.mute:
        description: Get access to mute somebody
        default: false